<a href="https://colab.research.google.com/github/skywalker0803r/CFB/blob/main/%E6%99%82%E9%96%93%E5%BA%8F%E5%88%97%E9%A0%90%E6%B8%ACmape16_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 載入數據

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/脫硫劑優化改善/20240916-CFB2脫硫劑優化改善.xlsx')
df

,Unnamed: 0,MLUT4_AIA792101A,MLUT4_AIA792101B,MLUT4_AIC-232B,MLUT4_AT-232A,MLUT4_AT-237,MLUT4_AT-240,MLUT4_AT-240A,MLUT4_FIC-231A,MLUT4_FIC-231B,...,MLUT4_TE-252F,MLUT4_TE-252G,MLUT4_TE-252H,MLUT4_TE-252I,MLUT4_ZT-231,MLUT4_ZT-232,DeSOx_1st,DeSOx_2nd,前爐SOx濃度,鈣硫比
0,datetime,ECO O2_A #2,ECO O2_B #2,ECO SOx #2,ECO NOx #2,煙囪O2_#2,煙囪SOx #2,煙囪SOx-A #2,飼料機A#2,飼料機B#2,...,上層爐溫F#2,上層爐溫G#2,上層爐溫H#2,上層爐溫I#2,PAF風門開度#2,SAF風門開度#2,NaN,NaN,NaN,NaN
1,2024-01-01 00:00:00,5.540932,6.8,67.034424,151.208024,9.623605,8.619934,8.619934,20.605973,0,...,876.984866,845.297084,845.703201,876.997523,59.200001,15,0.969941,0.871410,2230.093232,2.223152
2,2024-01-01 00:05:00,5.533478,6.8,66.662524,150.811453,9.616252,8.147002,8.147002,20.18102,0,...,875.326466,846.587071,844.10285,877.38106,59.200001,15,0.969979,0.877787,2220.527929,2.220789
3,2024-01-01 00:10:00,5.526025,6.8,64.320729,151.708113,9.608899,8.247992,8.247992,20.200619,0,...,875.675699,845.374599,843.500123,877.8976,59.200001,15,0.971249,0.871768,2237.129686,2.217612
4,2024-01-01 00:15:00,5.518571,6.801543,64.840762,151.283528,9.600898,7.60582,7.60582,20.220218,0,...,875.435828,845.10045,842.910508,874.888616,59.200001,15,0.970896,0.882700,2227.895501,2.214444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74588,2024-09-15 23:35:00,6.258452,5.140339,114.166438,209.520746,9.360355,13.105704,13.105704,12.795748,11.854892,...,916.635699,889.885541,906.016252,870.865216,100,26.103367,0.945172,0.885205,2082.274527,3.928554
74589,2024-09-15 23:40:00,6.284992,5.166336,106.669841,208.177318,9.280099,9.903673,9.903673,12.797045,11.862273,...,914.06561,889.042164,904.255862,869.007829,100,26.093265,0.948517,0.907156,2071.948976,3.927730
74590,2024-09-15 23:45:00,6.232171,5.225976,104.663595,211.564232,9.359701,9.345572,9.345572,12.798342,11.880556,...,913.978871,890.439554,903.442876,867.71297,100,26.1,0.949882,0.910708,2088.339754,3.928170
74591,2024-09-15 23:50:00,6.20333,5.14117,103.246788,206.570014,9.211132,8.303164,8.303164,12.799638,11.926489,...,913.419379,887.270132,903.808073,867.684024,100,26.078118,0.949256,0.919579,2034.665472,3.927928
74592,2024-09-15 23:55:00,6.007071,4.972081,110.111657,209.432213,9.231066,8.933592,8.933592,12.800935,11.864035,...,914.723621,889.081017,905.085873,868.045556,100,26.066269,0.946246,0.918868,2048.422596,3.928171

# 預處理

In [4]:
import numpy as np
def preprocess_df(df):
  # 索引處理
  df = df.set_index('Unnamed: 0')
  df.index.name = 'datetime'
  # 欄位處理
  df = df.iloc[1:,:]
  # 轉數值
  for i in df.columns:
    df[i] = pd.to_numeric(df[i], errors='coerce')
  # 處理無限大
  df = df.replace([np.inf, -np.inf], np.nan)
  return df
df_preprocessed = preprocess_df(df)
df_preprocessed

,MLUT4_AIA792101A,MLUT4_AIA792101B,MLUT4_AIC-232B,MLUT4_AT-232A,MLUT4_AT-237,MLUT4_AT-240,MLUT4_AT-240A,MLUT4_FIC-231A,MLUT4_FIC-231B,MLUT4_FIC-231C,...,MLUT4_TE-252F,MLUT4_TE-252G,MLUT4_TE-252H,MLUT4_TE-252I,MLUT4_ZT-231,MLUT4_ZT-232,DeSOx_1st,DeSOx_2nd,前爐SOx濃度,鈣硫比
datetime,,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:00:00,5.540932,6.800000,67.034424,151.208024,9.623605,8.619934,8.619934,20.605973,0.000000,17.456094,...,876.984866,845.297084,845.703201,876.997523,59.200001,15.000000,0.969941,0.871410,2230.093232,2.223152
2024-01-01 00:05:00,5.533478,6.800000,66.662524,150.811453,9.616252,8.147002,8.147002,20.181020,0.000000,17.449118,...,875.326466,846.587071,844.102850,877.381060,59.200001,15.000000,0.969979,0.877787,2220.527929,2.220789
2024-01-01 00:10:00,5.526025,6.800000,64.320729,151.708113,9.608899,8.247992,8.247992,20.200619,0.000000,17.442142,...,875.675699,845.374599,843.500123,877.897600,59.200001,15.000000,0.971249,0.871768,2237.129686,2.217612
2024-01-01 00:15:00,5.518571,6.801543,64.840762,151.283528,9.600898,7.605820,7.605820,20.220218,0.000000,17.571883,...,875.435828,845.100450,842.910508,874.888616,59.200001,15.000000,0.970896,0.882700,2227.895501,2.214444
2024-01-01 00:20:00,5.511117,6.819977,64.390831,150.994896,9.581994,6.110485,6.110485,20.549012,0.000000,17.339679,...,875.245400,846.058978,844.200021,878.416710,59.200001,15.000000,0.970878,0.905103,2211.052236,2.211285
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-15 23:35:00,6.258452,5.140339,114.166438,209.520746,9.360355,13.105704,13.105704,12.795748,11.854892,12.842200,...,916.635699,889.885541,906.016252,870.865216,100.000000,26.103367,0.945172,0.885205,2082.274527,3.928554
2024-09-15 23:40:00,6.284992,5.166336,106.669841,208.177318,9.280099,9.903673,9.903673,12.797045,11.862273,12.823741,...,914.065610,889.042164,904.255862,869.007829,100.000000,26.093265,0.948517,0.907156,2071.948976,3.927730
2024-09-15 23:45:00,6.232171,5.225976,104.663595,211.564232,9.359701,9.345572,9.345572,12.798342,11.880556,12.842696,...,913.978871,890.439554,903.442876,867.712970,100.000000,26.100000,0.949882,0.910708,2088.339754,3.928170
2024-09-15 23:50:00,6.203330,5.141170,103.246788,206.570014,9.211132,8.303164,8.303164,12.799638,11.926489,12.825216,...,913.419379,887.270132,903.808073,867.684024,100.000000,26.078118,0.949256,0.919579,2034.665472,3.927928
2024-09-15 23:55:00,6.007071,4.972081,110.111657,209.432213,9.231066,8.933592,8.933592,12.800935,11.864035,12.803276,...,914.723621,889.081017,905.085873,868.045556,100.000000,26.066269,0.946246,0.918868,2048.422596,3.928171

# 欄位定義

In [5]:
y_col = 'MLUT4_AT-240'
x_col = [
    'MLUT4_AIC-232B',
    'MLUT4_FT-957',
    'MLUT4_FIC-231C',
    'MLUT4_FT-956',
    'MLUT4_PIC-233',
    'MLUT4_FIC-233',
    '鈣硫比',
    'MLUT4_TE-252G',
    'MLUT4_AT-232A',
    '前爐SOx濃度',
]
#可變參數:飼料機ABC飼煤量分布、石灰石投入量、床料多寡(上下層壓差)
可變參數 = [#ABC飼煤量分布
  'MLUT4_FIC-231A',
  'MLUT4_FIC-231B',
  'MLUT4_FIC-231C',
  #石灰石投入量
  'MLUT4_RQ-2BTLS',
  #床料多寡(上下層壓差)
  'MLUT4_TE-251A',
  'MLUT4_TE-251B',
  'MLUT4_TE-251C',
  'MLUT4_TE-251D',
  'MLUT4_TE-251E',
  'MLUT4_TE-251F',
  'MLUT4_TE-251G',
  'MLUT4_TE-251H',
  'MLUT4_TE-251I',
  'MLUT4_TE-252A',
  'MLUT4_TE-252B',
  'MLUT4_TE-252C',
  'MLUT4_TE-252D',
  'MLUT4_TE-252E',
  'MLUT4_TE-252F',
  'MLUT4_TE-252G',
  'MLUT4_TE-252H',
  'MLUT4_TE-252I',
  ]
x_col = set(可變參數)|set(x_col)
x_col = list(x_col)
print(x_col)

['MLUT4_FT-956', 'MLUT4_TE-252C', 'MLUT4_FT-957', '鈣硫比', 'MLUT4_FIC-233', 'MLUT4_TE-251C', 'MLUT4_FIC-231B', 'MLUT4_TE-251G', 'MLUT4_TE-251E', 'MLUT4_TE-252A', 'MLUT4_PIC-233', 'MLUT4_TE-251D', 'MLUT4_RQ-2BTLS', 'MLUT4_FIC-231A', '前爐SOx濃度', 'MLUT4_TE-251F', 'MLUT4_TE-252H', 'MLUT4_AIC-232B', 'MLUT4_AT-232A', 'MLUT4_TE-251H', 'MLUT4_FIC-231C', 'MLUT4_TE-251A', 'MLUT4_TE-252I', 'MLUT4_TE-252G', 'MLUT4_TE-252B', 'MLUT4_TE-251B', 'MLUT4_TE-252D', 'MLUT4_TE-252F', 'MLUT4_TE-251I', 'MLUT4_TE-252E']

# 創建資料集

In [13]:
import pandas as pd
import numpy as np
from tqdm import tqdm

def create_dataset(df, time_step, x_col, y_col):
    X, y = [], []
    for start in tqdm(range(len(df) - time_step)):
        end = start + time_step

        # X: 從 start 到 start+time_step 的 x_col 和 y_col
        X_instance = df.iloc[start:end+1][x_col + [y_col]].values
        # mask y
        X_instance[-1,-1] = 0

        # y: 第 start+time_step 行的 y_col
        y_instance = df.iloc[end][y_col]

        # 檢查是否有缺失值
        if np.isnan(X_instance).any() or np.isnan(y_instance).any():
          continue

        X.append(X_instance)
        y.append(y_instance)
    return np.array(X), np.array(y)

time_step = 2
X, y = create_dataset(df_preprocessed, time_step, x_col, y_col)

100%|██████████| 74590/74590 [00:44<00:00, 1681.91it/s]

In [14]:
print(X.shape,y.shape)

(55439, 3, 31) (55439,)

In [15]:
X = X.reshape((X.shape[0], X.shape[1] * X.shape[2]))
print(X.shape,y.shape)

(55439, 93) (55439,)

# 建模

In [16]:
#!pip install catboost

In [17]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
import matplotlib.pyplot as plt
from catboost import CatBoostRegressor, Pool

# 分割資料
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 建立 CatBoost 模型（silent=True 不顯示訓練過程）
model = CatBoostRegressor(
    loss_function='MAE',  # 可選: 'MAE', 'RMSE' 等
    eval_metric='MAPE',
    iterations=1000,
    learning_rate=0.1,
    depth=6,
    verbose=100
)

model.fit(X_train, y_train, eval_set=(X_test, y_test))

# 預測
y_pred = model.predict(X_test)

result = pd.DataFrame({'y_test':y_test,'y_pred':y_pred})
result['r2'] = r2_score(result['y_test'], result['y_pred'])
result['rmse'] = np.sqrt(mean_squared_error(result['y_test'], result['y_pred']))
result['mape(%)'] = abs(result['y_test']-result['y_pred'])/result['y_test']*100
result = result.replace(np.inf,np.nan)
result.dropna(inplace=True)
result

0:	learn: 0.3964428	test: 0.4012343	best: 0.4012343 (0)	total: 80.5ms	remaining: 1m 20s
100:	learn: 0.1438452	test: 0.1473459	best: 0.1473459 (100)	total: 4.18s	remaining: 37.2s
200:	learn: 0.1247156	test: 0.1332216	best: 0.1332216 (200)	total: 8.65s	remaining: 34.4s
300:	learn: 0.1152800	test: 0.1285741	best: 0.1285741 (300)	total: 14.3s	remaining: 33.3s
400:	learn: 0.1087209	test: 0.1252861	best: 0.1252790 (399)	total: 19.2s	remaining: 28.6s
500:	learn: 0.1040015	test: 0.1232783	best: 0.1232783 (500)	total: 23s	remaining: 22.9s
600:	learn: 0.1003530	test: 0.1224658	best: 0.1224658 (600)	total: 28.6s	remaining: 19s
700:	learn: 0.0972287	test: 0.1220287	best: 0.1220200 (698)	total: 32.4s	remaining: 13.8s
800:	learn: 0.0945312	test: 0.1215762	best: 0.1215762 (800)	total: 36.2s	remaining: 9s
900:	learn: 0.0923125	test: 0.1210536	best: 0.1210197 (895)	total: 41.9s	remaining: 4.6s
999:	learn: 0.0904245	test: 0.1207263	best: 0.1207248 (998)	total: 45.7s	remaining: 0us

bestTest = 0.1207248073
bestIteration = 998

Shrink model to first 999 iterations.

          y_test     y_pred        r2      rmse    mape(%)
0      16.336979  15.135653  0.763875  3.216208   7.353419
1      16.177273  13.319615  0.763875  3.216208  17.664646
2      11.392375  11.715288  0.763875  3.216208   2.834469
3      10.252846  12.203952  0.763875  3.216208  19.029890
4       9.793209  10.804803  0.763875  3.216208  10.329543
...          ...        ...       ...       ...        ...
11083  12.607597  12.746473  0.763875  3.216208   1.101526
11084  12.073227  10.466502  0.763875  3.216208  13.308167
11085  14.131328  14.449248  0.763875  3.216208   2.249751
11086  17.986543  16.706775  0.763875  3.216208   7.115143
11087   8.784102   8.974505  0.763875  3.216208   2.167583

[11083 rows x 5 columns]

In [18]:
result.mean()

y_test     11.624986
y_pred     11.457551
r2          0.763875
rmse        3.216208
mape(%)    16.907371
dtype: float64

In [19]:
#n = 5 0.36%
#n = 20 24%